require "observing_night"

# ============================================================================
# DO NOT EDIT THIS FILE.
#
# These examples describe how observers talk about their own nights. If one is
# failing, the example is right and the code is wrong.
# ============================================================================
RSpec.describe Meridian::Exercise04::ObservingNight do
  describe ".covering" do
    it "files 21:00 on 18 September under the night of the 18th" do
      night = Meridian::Exercise04::ObservingNight.covering(
        Time.find_zone!("Europe/Prague").parse("2026-09-18 21:00").utc,
        time_zone: "Europe/Prague"
      )

      expect(night.date).to eq Date.new(2026, 9, 18)
    end

    it "files 02:00 on 19 September under the night of the 18th" do
      night = Meridian::Exercise04::ObservingNight.covering(
        Time.find_zone!("Europe/Prague").parse("2026-09-19 02:00").utc,
        time_zone: "Europe/Prague"
      )

      expect(night.date).to eq Date.new(2026, 9, 18)
    end

    it "files 05:00 on 19 September under the night of the 18th" do
      night = Meridian::Exercise04::ObservingNight.covering(
        Time.find_zone!("Europe/Prague").parse("2026-09-19 05:00").utc,
        time_zone: "Europe/Prague"
      )

      expect(night.date).to eq Date.new(2026, 9, 18)
    end

    it "files 21:00 in Honolulu under the observer's date, not UTC's" do
      night = Meridian::Exercise04::ObservingNight.covering(
        Time.find_zone!("Pacific/Honolulu").parse("2026-09-18 21:00").utc,
        time_zone: "Pacific/Honolulu"
      )

      expect(night.date).to eq Date.new(2026, 9, 18)
    end

    it "files 13:00 on 19 September under the night of the 19th" do
      night = Meridian::Exercise04::ObservingNight.covering(
        Time.find_zone!("Europe/Prague").parse("2026-09-19 13:00").utc,
        time_zone: "Europe/Prague"
      )

      expect(night.date).to eq Date.new(2026, 9, 19)
    end

    it "files 11:00 on 25 October under the night of the 24th" do
      night = Meridian::Exercise04::ObservingNight.covering(
        Time.find_zone!("Europe/Prague").parse("2026-10-25 11:00").utc,
        time_zone: "Europe/Prague"
      )

      expect(night.date).to eq Date.new(2026, 10, 24)
    end
  end

  describe "#window" do
    it "runs from midday on the 18th to midday on the 19th" do
      window = Meridian::Exercise04::ObservingNight.new(
        Date.new(2026, 9, 18), time_zone: "Europe/Prague"
      ).window

      expect(window.first.strftime("%Y-%m-%d %H:%M")).to eq "2026-09-18 12:00"
      expect(window.last.strftime("%Y-%m-%d %H:%M")).to eq "2026-09-19 12:00"
    end

    it "excludes its own end, so midday belongs to one night only" do
      fourteenth = Meridian::Exercise04::ObservingNight.new(
        Date.new(2026, 9, 18), time_zone: "Europe/Prague"
      ).window
      fifteenth = Meridian::Exercise04::ObservingNight.new(
        Date.new(2026, 9, 19), time_zone: "Europe/Prague"
      ).window
      midday = Time.find_zone!("Europe/Prague").parse("2026-09-19 12:00")

      expect(fifteenth).to cover(midday)
      expect(fourteenth).not_to cover(midday)
    end

    it "is 25 hours long for the night the clocks go back" do
      window = Meridian::Exercise04::ObservingNight.new(
        Date.new(2026, 10, 24), time_zone: "Europe/Prague"
      ).window

      expect((window.last - window.first) / 3600).to eq 25
    end

    it "starts at midday in Honolulu for a Honolulu observer" do
      window = Meridian::Exercise04::ObservingNight.new(
        Date.new(2026, 9, 18), time_zone: "Pacific/Honolulu"
      ).window

      midday = window.first.strftime("%Y-%m-%d %H:%M %z")

      expect(midday).to eq "2026-09-18 12:00 -1000"
    end
  end
end
