require "session_planner"

# ============================================================================
# DO NOT EDIT THIS FILE.
#
# Brno, 2026. The clocks go forward at 02:00 on 29 March and back at 03:00 on
# 25 October.
# ============================================================================
RSpec.describe Meridian::Exercise03::SessionPlanner do
  describe ".moments_for" do
    it "finds the one moment 21:00 on 14 July can mean" do
      observer = Meridian::Observer.new(
        name: "Tereza",
        time_zone: "Europe/Prague"
      )

      moments = Meridian::Exercise03::SessionPlanner.moments_for(
        observer: observer,
        local_time: "2026-07-14 21:00"
      )

      expect(moments.map(&:utc)).to eq [Time.utc(2026, 7, 14, 19, 0, 0)]
    end

    it "answers on the observer's own clock" do
      observer = Meridian::Observer.new(
        name: "Amy",
        time_zone: "Asia/Kathmandu"
      )

      moments = Meridian::Exercise03::SessionPlanner.moments_for(
        observer: observer,
        local_time: "2026-07-14 21:00"
      )

      expect(moments.map { |moment| moment.time_zone.name })
        .to eq ["Asia/Kathmandu"]
      expect(moments.map(&:utc)).to eq [Time.utc(2026, 7, 14, 15, 15, 0)]
    end

    it "finds both moments 02:30 on 25 October can mean, summer time first" do
      observer = Meridian::Observer.new(
        name: "Tereza",
        time_zone: "Europe/Prague"
      )

      moments = Meridian::Exercise03::SessionPlanner.moments_for(
        observer: observer,
        local_time: "2026-10-25 02:30"
      )

      expect(moments.map(&:utc)).to eq [
        Time.utc(2026, 10, 25, 0, 30, 0),
        Time.utc(2026, 10, 25, 1, 30, 0)
      ]
    end

    it "hands back both readings of 02:30, labelled, so a human can choose" do
      observer = Meridian::Observer.new(
        name: "Tereza",
        time_zone: "Europe/Prague"
      )

      moments = Meridian::Exercise03::SessionPlanner.moments_for(
        observer: observer,
        local_time: "2026-10-25 02:30"
      )

      expect(moments.map { |moment| moment.strftime("%H:%M %Z") })
        .to eq ["02:30 CEST", "02:30 CET"]
    end

    it "finds no moment at all for 02:30 on 29 March" do
      observer = Meridian::Observer.new(
        name: "Tereza",
        time_zone: "Europe/Prague"
      )

      moments = Meridian::Exercise03::SessionPlanner.moments_for(
        observer: observer, local_time: "2026-03-29 02:30"
      )

      expect(moments).to be_empty
    end

    it "finds one moment either side of the gap on 29 March" do
      observer = Meridian::Observer.new(
        name: "Tereza",
        time_zone: "Europe/Prague"
      )

      before = Meridian::Exercise03::SessionPlanner.moments_for(
        observer: observer,
        local_time: "2026-03-29 01:30"
      )
      after = Meridian::Exercise03::SessionPlanner.moments_for(
        observer: observer,
        local_time: "2026-03-29 03:30"
      )

      expect(before.map(&:utc)).to eq [Time.utc(2026, 3, 29, 0, 30, 0)]
      expect(after.map(&:utc)).to eq [Time.utc(2026, 3, 29, 1, 30, 0)]
    end
  end
end
