require "subscription"

# ============================================================================
# DO NOT EDIT THIS FILE.
# ============================================================================
RSpec.describe Meridian::Exercise02::Subscription do
  describe ".next_renewal_time" do
    it "renews a 15 January subscription on 15 February" do
      brno = Time.find_zone!("Europe/Prague")

      renewal = Meridian::Exercise02::Subscription.next_renewal_time(
        started_at: brno.parse("2026-01-15 09:00"),
        after: brno.parse("2026-01-20 09:00")
      ).in_time_zone(brno)

      expect(renewal.strftime("%Y-%m-%d")).to eq "2026-02-15"
    end

    it "renews two periods after 15 January on 15 March, not 16 March" do
      brno = Time.find_zone!("Europe/Prague")

      renewal = Meridian::Exercise02::Subscription.next_renewal_time(
        started_at: brno.parse("2026-01-15 09:00"),
        after: brno.parse("2026-02-20 09:00")
      ).in_time_zone(brno)

      expect(renewal.strftime("%Y-%m-%d")).to eq "2026-03-15"
    end

    it "clamps a 31 January subscription to 28 February" do
      brno = Time.find_zone!("Europe/Prague")

      renewal = Meridian::Exercise02::Subscription.next_renewal_time(
        started_at: brno.parse("2026-01-31 09:00"),
        after: brno.parse("2026-02-01 09:00")
      ).in_time_zone(brno)

      expect(renewal.strftime("%Y-%m-%d")).to eq "2026-02-28"
    end

    it "bills on 31 March again after February clamped it to the 28th" do
      brno = Time.find_zone!("Europe/Prague")

      renewal = Meridian::Exercise02::Subscription.next_renewal_time(
        started_at: brno.parse("2026-01-31 09:00"),
        after: brno.parse("2026-03-01 09:00")
      ).in_time_zone(brno)

      expect(renewal.strftime("%Y-%m-%d")).to eq "2026-03-31"
    end

    it "clamps a 29 February subscription to 28 February in a common year" do
      brno = Time.find_zone!("Europe/Prague")

      renewal = Meridian::Exercise02::Subscription.next_renewal_time(
        started_at: brno.parse("2024-02-29 09:00"),
        after: brno.parse("2026-02-01 09:00")
      ).in_time_zone(brno)

      expect(renewal.strftime("%Y-%m-%d")).to eq "2026-02-28"
    end

    it "still bills at 09:00 Brno time after the clocks go forward" do
      brno = Time.find_zone!("Europe/Prague")

      renewal = Meridian::Exercise02::Subscription.next_renewal_time(
        started_at: brno.parse("2026-03-15 09:00"),
        after: brno.parse("2026-04-01 09:00")
      ).in_time_zone(brno)

      expect(renewal.strftime("%Y-%m-%d %H:%M")).to eq "2026-04-15 09:00"
    end

    it "skips a renewal that falls exactly now" do
      brno = Time.find_zone!("Europe/Prague")
      after = brno.parse("2026-02-15 09:00")

      renewal = Meridian::Exercise02::Subscription.next_renewal_time(
        started_at: brno.parse("2026-01-15 09:00"),
        after: after
      ).in_time_zone(brno)

      expect(renewal).to be > after
    end
  end
end
