require "booking"

# ============================================================================
# DO NOT EDIT THIS FILE.
#
# These examples describe what observers expect to happen. If one is failing,
# the example is right and the code is wrong.
# ============================================================================
RSpec.describe Meridian::Exercise01::Booking do
  describe ".call" do
    it "books 21:00 in Brno (UTC+02:00 in September) as 19:00 UTC" do
      observer = Meridian::Observer.new(
        name: "Tereza", time_zone: "Europe/Prague"
      )

      session = Meridian::Exercise01::Booking.call(
        observer: observer,
        target: "the Moon",
        local_starts_at: "2026-09-18 21:00"
      )

      expect(session.starts_at.utc).to eq Time.utc(2026, 9, 18, 19, 0, 0)
    end

    it "books 21:00 in Brno (UTC+01:00 in December) as 20:00 UTC" do
      observer = Meridian::Observer.new(
        name: "Tereza", time_zone: "Europe/Prague"
      )

      session = Meridian::Exercise01::Booking.call(
        observer: observer,
        target: "Jupiter",
        local_starts_at: "2026-12-18 21:00"
      )

      expect(session.starts_at.utc).to eq Time.utc(2026, 12, 18, 20, 0, 0)
    end

    it "books 21:00 in Kathmandu (UTC+05:45) as 15:15 UTC" do
      observer = Meridian::Observer.new(
        name: "Binod", time_zone: "Asia/Kathmandu"
      )

      session = Meridian::Exercise01::Booking.call(
        observer: observer,
        target: "Mars",
        local_starts_at: "2026-05-20 21:00"
      )

      expect(session.starts_at.utc).to eq Time.utc(2026, 5, 20, 15, 15, 0)
    end

    it "raises InvalidTime when the input is not a time" do
      observer = Meridian::Observer.new(
        name: "Tereza", time_zone: "Europe/Prague"
      )

      expect {
        Meridian::Exercise01::Booking.call(
          observer: observer,
          target: "the Moon",
          local_starts_at: "tomorrow evening-ish"
        )
      }.to raise_error Meridian::InvalidTime
    end

    it "raises when the observer's time zone is not a zone" do
      observer = Meridian::Observer.new(
        name: "Tereza", time_zone: "Europe/Pariis"
      )

      expect {
        Meridian::Exercise01::Booking.call(
          observer: observer,
          target: "Jupiter",
          local_starts_at: "2026-09-18 21:00"
        )
      }.to raise_error ArgumentError
    end
  end
end
