require "time_formatter"

# ============================================================================
# DO NOT EDIT THIS FILE.
# ============================================================================
RSpec.describe Meridian::Exercise00::TimeFormatter do
  describe ".format" do
    it "formats 21:00 on 18 September 2026 as 'September 18, 2026 at 21:00'" do
      time = Time.utc(2026, 9, 18, 21, 0, 0)

      formatted = Meridian::Exercise00::TimeFormatter.format(time)

      expect(formatted).to eq "September 18, 2026 at 21:00"
    end
  end
end
