require "schedule"

# ============================================================================
# DO NOT EDIT THIS FILE.
# ============================================================================
RSpec.describe Meridian::Exercise05::Schedule do
  it "sends every reminder at 21:00 through an unchanging week in Brno" do
    brno = Time.find_zone!("Europe/Prague")

    runs = Meridian::Exercise05::Schedule
      .daily_at(hour: 21, time_zone: "Europe/Prague")
      .next_runs(count: 5, from: brno.parse("2026-01-12 08:00"))

    expect(runs.map { |run| run.utc.strftime("%F %H:%M") }).to eq [
      "2026-01-12 20:00",
      "2026-01-13 20:00",
      "2026-01-14 20:00",
      "2026-01-15 20:00",
      "2026-01-16 20:00"
    ]
  end

  it "sends every reminder at 21:00 across the spring forward in Brno" do
    brno = Time.find_zone!("Europe/Prague")

    runs = Meridian::Exercise05::Schedule
      .daily_at(hour: 21, time_zone: "Europe/Prague")
      .next_runs(count: 5, from: brno.parse("2026-03-27 08:00"))

    expect(runs.map { |run| run.utc.strftime("%F %H:%M") }).to eq [
      "2026-03-27 20:00",
      "2026-03-28 20:00",
      "2026-03-29 19:00",
      "2026-03-30 19:00",
      "2026-03-31 19:00"
    ]
  end

  it "sends every reminder at 21:00 in Kathmandu, which has no daylight saving" do
    kathmandu = Time.find_zone!("Asia/Kathmandu")

    runs = Meridian::Exercise05::Schedule
      .daily_at(hour: 21, time_zone: "Asia/Kathmandu")
      .next_runs(count: 5, from: kathmandu.parse("2026-05-18 08:00"))

    expect(runs.map { |run| run.utc.strftime("%F %H:%M") }).to eq [
      "2026-05-18 15:15",
      "2026-05-19 15:15",
      "2026-05-20 15:15",
      "2026-05-21 15:15",
      "2026-05-22 15:15"
    ]
  end

  it "sends every reminder at 21:00 through a September week in Vancouver" do
    vancouver = Time.find_zone!("America/Vancouver")

    runs = Meridian::Exercise05::Schedule
      .daily_at(hour: 21, time_zone: "America/Vancouver")
      .next_runs(count: 5, from: vancouver.parse("2026-09-14 08:00"))

    expect(runs.map { |run| run.utc.strftime("%F %H:%M") }).to eq [
      "2026-09-15 04:00",
      "2026-09-16 04:00",
      "2026-09-17 04:00",
      "2026-09-18 04:00",
      "2026-09-19 04:00"
    ]
  end

  it "sends every reminder at 21:00 in Vancouver across the first of November" do
    vancouver = Time.find_zone!("America/Vancouver")

    runs = Meridian::Exercise05::Schedule
      .daily_at(hour: 21, time_zone: "America/Vancouver")
      .next_runs(count: 5, from: vancouver.parse("2026-10-30 08:00"))

    expect(runs.map { |run| run.utc.strftime("%F %H:%M") }).to eq [
      "2026-10-31 04:00",
      "2026-11-01 04:00",
      "2026-11-02 04:00",
      "2026-11-03 04:00",
      "2026-11-04 04:00"
    ]
  end

  it "spaces the reminders either side of the first of November 24 hours apart" do
    vancouver = Time.find_zone!("America/Vancouver")

    runs = Meridian::Exercise05::Schedule
      .daily_at(hour: 21, time_zone: "America/Vancouver")
      .next_runs(count: 5, from: vancouver.parse("2026-10-30 08:00"))

    expect(runs.each_cons(2).map { |a, b| ((b.utc - a.utc) / 3600).round })
      .to eq [24, 24, 24, 24]
  end

  it "names the zone the observer in Vancouver is in on the night in question" do
    vancouver = Time.find_zone!("America/Vancouver")

    runs = Meridian::Exercise05::Schedule
      .daily_at(hour: 21, time_zone: "America/Vancouver")
      .next_runs(count: 5, from: vancouver.parse("2026-10-30 08:00"))

    expect(runs.map { |run| run.in_time_zone(vancouver).strftime("%F %H:%M %Z") })
      .to eq [
        "2026-10-30 21:00 PDT",
        "2026-10-31 21:00 PDT",
        "2026-11-01 21:00 MST",
        "2026-11-02 21:00 MST",
        "2026-11-03 21:00 MST"
      ]
  end

  it "sends every reminder at 21:00 through a December week in Vancouver" do
    vancouver = Time.find_zone!("America/Vancouver")

    runs = Meridian::Exercise05::Schedule
      .daily_at(hour: 21, time_zone: "America/Vancouver")
      .next_runs(count: 5, from: vancouver.parse("2026-12-07 08:00"))

    expect(runs.map { |run| run.utc.strftime("%F %H:%M") }).to eq [
      "2026-12-08 04:00",
      "2026-12-09 04:00",
      "2026-12-10 04:00",
      "2026-12-11 04:00",
      "2026-12-12 04:00"
    ]
  end

  it "sends every reminder at 21:00 in Vancouver the following March" do
    vancouver = Time.find_zone!("America/Vancouver")

    runs = Meridian::Exercise05::Schedule
      .daily_at(hour: 21, time_zone: "America/Vancouver")
      .next_runs(count: 5, from: vancouver.parse("2027-03-12 08:00"))

    expect(runs.map { |run| run.utc.strftime("%F %H:%M") }).to eq [
      "2027-03-13 04:00",
      "2027-03-14 04:00",
      "2027-03-15 04:00",
      "2027-03-16 04:00",
      "2027-03-17 04:00"
    ]
  end
end
